create extension if not exists pg_trgm;
create extension if not exists btree_gist;

create table public.seed_info (
  scale text not null,
  seeded_at timestamptz not null default now()
);

create schema core;

create table core.organizations (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  city text not null,
  kvk_number text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table core.users (
  id integer generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  email text not null,
  name text not null,
  role text not null check (role in ('admin', 'manager', 'finance', 'maintenance')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, email)
);

create index users_role_idx on core.users (organization_id, role);
