create schema portfolio;

create table portfolio.amenities (
  code text primary key,
  name text not null
);

create table portfolio.owners (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  name text not null,
  kind text not null check (kind in ('private', 'company', 'pension_fund', 'housing_association')),
  email text,
  phone text,
  iban text not null,
  management_fee_percent numeric(4, 2) not null default 6 check (management_fee_percent between 0 and 20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index owners_organization_idx on portfolio.owners (organization_id, created_at);
create index owners_kind_idx on portfolio.owners (organization_id, kind);
create index owners_name_trgm_idx on portfolio.owners using gin (name gin_trgm_ops);

create table portfolio.properties (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  owner_id bigint not null references portfolio.owners (id),
  name text not null,
  kind text not null check (kind in ('apartment_building', 'single_family', 'mixed_use')),
  street text not null,
  house_number text not null,
  postal_code text not null check (postal_code ~ '^[1-9][0-9]{3} [A-Z]{2}$'),
  city text not null,
  latitude numeric(8, 6) not null check (latitude between -90 and 90),
  longitude numeric(9, 6) not null check (longitude between -180 and 180),
  built_year smallint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index properties_organization_idx on portfolio.properties (organization_id, created_at);
create index properties_owner_idx on portfolio.properties (owner_id);
create index properties_city_idx on portfolio.properties (organization_id, city);
create index properties_kind_idx on portfolio.properties (organization_id, kind);
create index properties_location_idx on portfolio.properties (latitude, longitude);
create index properties_name_trgm_idx on portfolio.properties using gin (name gin_trgm_ops);

create table portfolio.units (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  property_id bigint not null references portfolio.properties (id),
  label text not null,
  floor smallint not null default 0,
  bedrooms smallint not null check (bedrooms >= 0),
  area_m2 integer not null check (area_m2 > 0),
  energy_label text not null check (energy_label in ('A++++', 'A+++', 'A++', 'A+', 'A', 'B', 'C', 'D', 'E', 'F', 'G')),
  base_rent numeric(10, 2) not null check (base_rent > 0),
  status text not null default 'vacant' check (status in ('let', 'vacant', 'renovation')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (property_id, label)
);

create index units_organization_idx on portfolio.units (organization_id, created_at);
create index units_status_idx on portfolio.units (organization_id, status);
create index units_rent_idx on portfolio.units (organization_id, base_rent);
create index units_energy_label_idx on portfolio.units (organization_id, energy_label);

create table portfolio.unit_amenities (
  unit_id bigint not null references portfolio.units (id),
  amenity_code text not null references portfolio.amenities (code),
  organization_id integer not null references core.organizations (id),
  added_at timestamptz not null default now(),
  primary key (unit_id, amenity_code)
);

create index unit_amenities_amenity_idx on portfolio.unit_amenities (amenity_code);
create index unit_amenities_organization_idx on portfolio.unit_amenities (organization_id);

-- Valuations over time: the yearly WOZ value every property gets, and the odd appraisal.
create table portfolio.valuations (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  property_id bigint not null references portfolio.properties (id),
  valued_on date not null,
  value numeric(14, 2) not null check (value > 0),
  source text not null check (source in ('woz', 'appraisal')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (property_id, source, valued_on)
);

create index valuations_organization_idx on portfolio.valuations (organization_id, valued_on);
create index valuations_source_idx on portfolio.valuations (organization_id, source);

create index units_label_trgm_idx on portfolio.units using gin (label gin_trgm_ops);
