create schema leasing;

create table leasing.tenants (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  date_of_birth date not null,
  iban text not null,
  monthly_income numeric(10, 2) not null check (monthly_income >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index tenants_organization_idx on leasing.tenants (organization_id, created_at);
create index tenants_last_name_trgm_idx on leasing.tenants using gin (last_name gin_trgm_ops);
create index tenants_email_trgm_idx on leasing.tenants using gin (email gin_trgm_ops);

-- end_date is the last day of the tenancy, null while it runs for an indefinite term.
-- Two leases of one unit never overlap: Postgres refuses the second with an exclusion constraint.
create table leasing.leases (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  number text not null,
  unit_id bigint not null references portfolio.units (id),
  term text not null check (term in ('indefinite', 'fixed')),
  start_date date not null,
  end_date date,
  monthly_rent numeric(10, 2) not null check (monthly_rent > 0),
  service_costs numeric(10, 2) not null default 0 check (service_costs >= 0),
  notice_given_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, number),
  check (end_date is null or end_date >= start_date),
  check (term = 'indefinite' or end_date is not null),
  constraint leases_no_overlap exclude using gist (unit_id with =, daterange(start_date, end_date, '[]') with &&)
);

create index leases_organization_idx on leasing.leases (organization_id, created_at);
create index leases_unit_idx on leasing.leases (unit_id);
create index leases_start_idx on leasing.leases (organization_id, start_date);
create index leases_end_idx on leasing.leases (organization_id, end_date);

-- Everyone who signed a lease: one primary tenant, and co-signers.
create table leasing.lease_tenants (
  lease_id bigint not null references leasing.leases (id),
  tenant_id bigint not null references leasing.tenants (id),
  organization_id integer not null references core.organizations (id),
  role text not null check (role in ('primary', 'co_signer')),
  added_at timestamptz not null default now(),
  primary key (lease_id, tenant_id)
);

create unique index lease_tenants_primary_idx on leasing.lease_tenants (lease_id) where role = 'primary';
create index lease_tenants_tenant_idx on leasing.lease_tenants (tenant_id);
create index lease_tenants_organization_idx on leasing.lease_tenants (organization_id);

create table leasing.deposits (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  lease_id bigint not null unique references leasing.leases (id),
  amount numeric(10, 2) not null check (amount > 0),
  received_on date not null,
  status text not null default 'held' check (status in ('held', 'returned', 'partially_returned', 'withheld')),
  returned_amount numeric(10, 2) not null default 0 check (returned_amount >= 0 and returned_amount <= amount),
  returned_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((status = 'held') = (returned_on is null))
);

create index deposits_organization_idx on leasing.deposits (organization_id, created_at);
create index deposits_status_idx on leasing.deposits (organization_id, status);

create index leases_number_trgm_idx on leasing.leases using gin (number gin_trgm_ops);
