create schema billing;

-- One charge per lease and month, due on the first. paid_amount is the sum of its payments, kept by the triggers
-- below; the check on it means the payments of a charge never add up to more than the charge.
create table billing.rent_charges (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  lease_id bigint not null references leasing.leases (id),
  period date not null check (extract(day from period) = 1),
  due_on date not null,
  description text not null,
  amount numeric(10, 2) not null check (amount > 0),
  paid_amount numeric(10, 2) not null default 0 check (paid_amount >= 0 and paid_amount <= amount),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lease_id, period)
);

create index rent_charges_organization_idx on billing.rent_charges (organization_id, period);
create index rent_charges_due_idx on billing.rent_charges (organization_id, due_on);
create index rent_charges_amount_idx on billing.rent_charges (organization_id, amount);
-- The open charges, a few percent of the table: what the arrears view reads.
create index rent_charges_open_idx on billing.rent_charges (organization_id, lease_id) where paid_amount < amount;

create table billing.payments (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  charge_id bigint not null references billing.rent_charges (id),
  paid_on date not null,
  amount numeric(10, 2) not null check (amount > 0),
  method text not null check (method in ('direct_debit', 'bank_transfer', 'ideal')),
  reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index payments_charge_idx on billing.payments (charge_id);
create index payments_organization_idx on billing.payments (organization_id, paid_on);
create index payments_method_idx on billing.payments (organization_id, method);

create function billing.refresh_paid_amounts(ids bigint[]) returns void language sql as $$
  update billing.rent_charges c
  set paid_amount = s.paid, updated_at = now()
  from (
    select ch.id, coalesce((select sum(p.amount) from billing.payments p where p.charge_id = ch.id), 0) as paid
    from billing.rent_charges ch
    where ch.id = any (ids)
  ) s
  where c.id = s.id and c.paid_amount is distinct from s.paid
$$;

create function billing.payments_inserted() returns trigger language plpgsql as $$
begin
  perform billing.refresh_paid_amounts(array(select distinct charge_id from new_rows));
  return null;
end $$;

create function billing.payments_updated() returns trigger language plpgsql as $$
begin
  perform billing.refresh_paid_amounts(array(select charge_id from old_rows union select charge_id from new_rows));
  return null;
end $$;

create function billing.payments_deleted() returns trigger language plpgsql as $$
begin
  perform billing.refresh_paid_amounts(array(select distinct charge_id from old_rows));
  return null;
end $$;

-- Transition tables cannot be combined with several events, so one trigger per event.
create trigger payments_inserted after insert on billing.payments
  referencing new table as new_rows for each statement execute function billing.payments_inserted();
create trigger payments_updated after update on billing.payments
  referencing old table as old_rows new table as new_rows for each statement execute function billing.payments_updated();
create trigger payments_deleted after delete on billing.payments
  referencing old table as old_rows for each statement execute function billing.payments_deleted();

-- Outstanding balance per lease: every charge minus its payments, for leases that still owe something.
create view billing.arrears as
select
  c.lease_id,
  c.organization_id,
  count(*)::integer as open_charges,
  sum(c.amount - c.paid_amount) as balance,
  min(c.due_on) as oldest_due_on
from billing.rent_charges c
where c.paid_amount < c.amount
group by c.lease_id, c.organization_id;
