create schema maintenance;

create type maintenance.ticket_status as enum ('reported', 'scheduled', 'done', 'cancelled');

create table maintenance.vendors (
  id integer generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  name text not null,
  trade text not null check (trade in ('plumbing', 'heating', 'electrical', 'roofing', 'carpentry', 'locksmith', 'pest_control', 'general')),
  email text,
  phone text,
  hourly_rate numeric(8, 2) not null check (hourly_rate > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index vendors_trade_idx on maintenance.vendors (organization_id, trade);

create table maintenance.tickets (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  number text not null,
  property_id bigint not null references portfolio.properties (id),
  unit_id bigint references portfolio.units (id),
  reported_by bigint references leasing.tenants (id),
  assigned_to integer references core.users (id),
  category text not null check (category in ('heating', 'plumbing', 'electrical', 'leak', 'mould', 'locks', 'appliances', 'windows_doors', 'garden', 'pests')),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  status maintenance.ticket_status not null default 'reported',
  title text not null,
  description text,
  reported_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, number),
  check ((status in ('done', 'cancelled')) = (closed_at is not null))
);

create index tickets_organization_idx on maintenance.tickets (organization_id, created_at);
create index tickets_status_idx on maintenance.tickets (organization_id, status);
create index tickets_priority_idx on maintenance.tickets (organization_id, priority);
create index tickets_category_idx on maintenance.tickets (organization_id, category);
create index tickets_reported_idx on maintenance.tickets (organization_id, reported_at);
create index tickets_property_idx on maintenance.tickets (property_id);
create index tickets_unit_idx on maintenance.tickets (unit_id);
create index tickets_reported_by_idx on maintenance.tickets (reported_by);
create index tickets_assigned_idx on maintenance.tickets (assigned_to);
create index tickets_title_trgm_idx on maintenance.tickets using gin (title gin_trgm_ops);

-- A ticket moves forward only: reported -> scheduled -> done, and reported or scheduled -> cancelled.
-- Closing it stamps closed_at; the check on the table keeps the two in step.
create function maintenance.ticket_status_changed() returns trigger language plpgsql as $$
begin
  if new.status = old.status then return new; end if;
  if not ((old.status = 'reported' and new.status in ('scheduled', 'cancelled'))
       or (old.status = 'scheduled' and new.status in ('done', 'cancelled'))) then
    raise exception 'a ticket cannot go from % to %', old.status, new.status using errcode = 'check_violation';
  end if;
  if new.status in ('done', 'cancelled') then new.closed_at := coalesce(new.closed_at, now()); end if;
  return new;
end $$;

create trigger ticket_status_changed before update of status on maintenance.tickets
  for each row execute function maintenance.ticket_status_changed();

create table maintenance.work_orders (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  ticket_id bigint not null references maintenance.tickets (id),
  vendor_id integer not null references maintenance.vendors (id),
  scheduled_for date not null,
  completed_on date,
  hours numeric(5, 2),
  cost numeric(10, 2),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (completed_on is null or completed_on >= scheduled_for)
);

create index work_orders_ticket_idx on maintenance.work_orders (ticket_id);
create index work_orders_vendor_idx on maintenance.work_orders (vendor_id);
create index work_orders_scheduled_idx on maintenance.work_orders (organization_id, scheduled_for);

create table maintenance.inspections (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  unit_id bigint not null references portfolio.units (id),
  lease_id bigint references leasing.leases (id),
  inspector_id integer not null references core.users (id),
  kind text not null check (kind in ('move_in', 'move_out', 'periodic')),
  inspected_on date not null,
  condition text not null check (condition in ('good', 'fair', 'poor')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index inspections_organization_idx on maintenance.inspections (organization_id, inspected_on);
create index inspections_unit_idx on maintenance.inspections (unit_id);
create index inspections_lease_idx on maintenance.inspections (lease_id);
create index inspections_inspector_idx on maintenance.inspections (inspector_id);
create index inspections_kind_idx on maintenance.inspections (organization_id, kind);
