export { compileFilter, type CompileOptions } from './compile-filter'
export { listQuery, buildListQuery, maxLimit, type ListResult, type ListPlan, type ListOptions, type ExtraColumn } from './list-query'
export { estimateCount } from './estimate-count'
export { exactCount } from './exact-count'
export { facetCounts, type FacetCount, type FacetOptions } from './facet-counts'
export { series, type Granularity, type SeriesOptions, type SeriesPoint } from './series'
export { histogram, type Histogram, type HistogramBucket } from './histogram'
export { scrollMode, type ScrollMode } from './scroll-mode'
export { explainGuard, type GuardFinding, type GuardOptions, type GuardReport } from './explain-guard'
export { QueryError, type QueryErrorCode } from './errors'
export type { Db } from './db'
export type { Scope } from './scope'
export { seekToPosition, type SeekRequest } from './seek-to-position'
