create extension if not exists pg_trgm;
create extension if not exists ltree;

create table public.seed_info (
  scale text not null,
  seeded_at timestamptz not null default now()
);

create schema core;

create table core.countries (
  code text primary key,
  name text not null,
  eu_member boolean not null default false
);

create table core.currencies (
  code text primary key,
  name text not null,
  symbol text not null,
  decimals smallint not null default 2
);

create table core.organizations (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  country_code text not null references core.countries (code),
  currency_code text not null references core.currencies (code),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table core.users (
  id integer generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  email text not null,
  name text not null,
  role text not null check (role in ('admin', 'sales', 'finance', 'warehouse')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, email)
);

create index users_role_idx on core.users (organization_id, role);
create index organizations_country_idx on core.organizations (country_code);
create index organizations_currency_idx on core.organizations (currency_code);
