create schema crm;

create table crm.companies (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  name text not null,
  country_code text not null references core.countries (code),
  city text not null,
  vat_number text,
  email text,
  phone text,
  status text not null default 'active' check (status in ('lead', 'active', 'dormant')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index companies_organization_idx on crm.companies (organization_id, created_at);
create index companies_country_idx on crm.companies (country_code);
create index companies_status_idx on crm.companies (organization_id, status);
create index companies_name_trgm_idx on crm.companies using gin (name gin_trgm_ops);

create table crm.people (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  company_id bigint not null references crm.companies (id),
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  job_title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index people_company_idx on crm.people (company_id);
create index people_organization_idx on crm.people (organization_id, created_at);

create table crm.tags (
  id integer generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  name text not null,
  color text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table crm.company_tags (
  company_id bigint not null references crm.companies (id),
  tag_id integer not null references crm.tags (id),
  organization_id integer not null references core.organizations (id),
  added_by integer references core.users (id),
  added_at timestamptz not null default now(),
  primary key (company_id, tag_id)
);

create index company_tags_tag_idx on crm.company_tags (tag_id);
create index company_tags_organization_idx on crm.company_tags (organization_id);
create index company_tags_added_by_idx on crm.company_tags (added_by);
