create schema catalog;

create table catalog.categories (
  id integer generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  parent_id integer references catalog.categories (id),
  name text not null,
  slug text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug)
);

create index categories_parent_idx on catalog.categories (parent_id, position);

create table catalog.products (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  category_id integer not null references catalog.categories (id),
  sku text not null,
  name text not null,
  description text,
  price numeric(12, 2) not null check (price >= 0),
  currency_code text not null references core.currencies (code),
  attributes jsonb not null default '{}',
  active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, sku)
);

create index products_category_idx on catalog.products (category_id);
create index products_organization_idx on catalog.products (organization_id, created_at);
create index products_name_trgm_idx on catalog.products using gin (name gin_trgm_ops);
create index products_attributes_idx on catalog.products using gin (attributes jsonb_path_ops);
create index products_live_idx on catalog.products (organization_id) where deleted_at is null;
