create schema sales;

create type sales.invoice_status as enum ('draft', 'sent', 'paid', 'overdue');

create table sales.orders (
  id uuid primary key default uuidv7(),
  organization_id integer not null references core.organizations (id),
  number text not null,
  company_id bigint not null references crm.companies (id),
  person_id bigint references crm.people (id),
  owner_id integer not null references core.users (id),
  status text not null check (status in ('draft', 'confirmed', 'picking', 'shipped', 'delivered', 'cancelled')),
  currency_code text not null references core.currencies (code),
  discount_percent numeric(5, 2) not null default 0,
  total numeric(14, 2) not null default 0,
  paid boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, number)
);

create index orders_organization_idx on sales.orders (organization_id, created_at);
create index orders_company_idx on sales.orders (company_id);
create index orders_person_idx on sales.orders (person_id);
create index orders_owner_idx on sales.orders (owner_id);
create index orders_status_idx on sales.orders (organization_id, status);
create index orders_created_idx on sales.orders (created_at);

create table sales.order_lines (
  order_id uuid not null references sales.orders (id),
  line_no integer not null,
  organization_id integer not null references core.organizations (id),
  product_id bigint not null references catalog.products (id),
  description text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (order_id, line_no)
);

create index order_lines_product_idx on sales.order_lines (product_id);
create index order_lines_organization_idx on sales.order_lines (organization_id);

create table sales.invoices (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  number text not null,
  order_id uuid references sales.orders (id),
  company_id bigint not null references crm.companies (id),
  status sales.invoice_status not null default 'draft',
  issued_at date not null,
  due_at date not null,
  vat_rate numeric(4, 2) not null default 21,
  subtotal numeric(14, 2) not null,
  vat numeric(14, 2) not null,
  total numeric(14, 2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, number)
);

create index invoices_organization_idx on sales.invoices (organization_id, created_at);
create index invoices_company_idx on sales.invoices (company_id);
create index invoices_order_idx on sales.invoices (order_id);
create index invoices_status_idx on sales.invoices (organization_id, status);
create index invoices_due_idx on sales.invoices (due_at) where status in ('sent', 'overdue');

create table sales.invoice_lines (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references sales.invoices (id),
  organization_id integer not null references core.organizations (id),
  position integer not null,
  product_id bigint references catalog.products (id),
  description text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null,
  line_total numeric(14, 2) generated always as (quantity * unit_price) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (invoice_id, position)
);

create index invoice_lines_product_idx on sales.invoice_lines (product_id);
create index invoice_lines_organization_idx on sales.invoice_lines (organization_id);
