create schema inventory;

create table inventory.warehouses (
  id integer generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  code text not null,
  name text not null,
  city text not null,
  country_code text not null references core.countries (code),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, code)
);

create index warehouses_country_idx on inventory.warehouses (country_code);

create table inventory.locations (
  id integer generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  warehouse_id integer not null references inventory.warehouses (id),
  path ltree not null,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (warehouse_id, path)
);

create index locations_organization_idx on inventory.locations (organization_id);
create index locations_path_idx on inventory.locations using gist (path);

-- Append-only ledger: rows are never updated, so there is no updated_at.
create table inventory.stock_moves (
  id bigint generated by default as identity primary key,
  organization_id integer not null references core.organizations (id),
  product_id bigint not null references catalog.products (id),
  warehouse_id integer not null references inventory.warehouses (id),
  location_id integer not null references inventory.locations (id),
  kind text not null check (kind in ('receipt', 'issue', 'transfer', 'adjustment')),
  quantity integer not null check (quantity <> 0),
  unit_cost numeric(12, 2) not null,
  reference text,
  moved_at timestamptz not null,
  user_id integer references core.users (id)
);

create index stock_moves_moved_at_idx on inventory.stock_moves (moved_at);
create index stock_moves_organization_idx on inventory.stock_moves (organization_id, moved_at);
create index stock_moves_product_idx on inventory.stock_moves (product_id, moved_at);
create index stock_moves_warehouse_idx on inventory.stock_moves (warehouse_id);
create index stock_moves_location_idx on inventory.stock_moves (location_id);
create index stock_moves_user_idx on inventory.stock_moves (user_id);
create index stock_moves_kind_idx on inventory.stock_moves (kind);

-- Derived from stock_moves: on-hand quantity per product and location.
create table inventory.stock_levels (
  product_id bigint not null references catalog.products (id),
  location_id integer not null references inventory.locations (id),
  organization_id integer not null references core.organizations (id),
  quantity integer not null,
  updated_at timestamptz not null default now(),
  primary key (product_id, location_id)
);

create index stock_levels_location_idx on inventory.stock_levels (location_id);
create index stock_levels_organization_idx on inventory.stock_levels (organization_id);
